# Generated by Django 6.0.5 on 2026-06-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_internship_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='Intership_certificates/'),
        ),
    ]
